services:
  bot:
    image:
    hostname: bot
    container_name: bot
    restart: always
    env_file:
      - ./.env
    logging:
      driver: "json-file"
      options:
        max-size: "10m"

  postgres:
    image: postgres:16.3
    hostname: postgres
    container_name: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "${HOST_IP}:23556:5432"
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"

volumes:
  postgres-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /путь/путь/postgres-data
